### PR TITLE
allow filetree alternate formats (v2)

### PR DESCRIPTION
**Pull request by estebanlm**

### CODE REVIEW

**Comment by estebanlm** [comment]
ping @dalehenrich :)
I need some help to fix the gemstone part.

**Comment by dalehenrich** [comment]
@estebanlm, I took a quick look at some of the failures and it looks like the method #detect:ifFound: is being used and it is not implemented in GemStone ... unfortunately I don't have the time to spend to turn the crank on a new GLASS release that would include this.

It would especially be problematic because I expect Metacello to be portable to old versions of Pharo and Squeak as well as GemStone, so it is not even practical to consider back porting #detect:ifFound: to all of the platforms that Metacello runs on today ...

It's probably best if you change the code you've added and use more portable methods ...

**Comment by jecisc** [comment]
@dalehenrich I did some correction on my fork and now I get this error:

```Smalltalk
a MessageNotUnderstood occurred (error 2010), a Set does not understand  #'handles:'
1 SCIGemStoneTestRunner >> stackTraceString:of: @3 line 2  [GsNMethod 209095937]
2 [] in  ExecBlock1 (SCITestRunner) >> runCase: @39 line 11  [GsNMethod 221486593]
3 MessageNotUnderstood (AbstractException) >> _executeOuterHandler: @4 line 7  [GsNMethod 4482561]
4 MessageNotUnderstood (AbstractException) >> _pass:with: @5 line 13  [GsNMethod 4478721]
5 MessageNotUnderstood (AbstractException) >> pass @2 line 14  [GsNMethod 4477697]
6 [] in  ExecBlock1 (MetacelloCommonMCSpecLoader) >> retryingResolvePackageSpecReferences:gofer: @56 line 27  [GsNMethod 130908161]
7 MessageNotUnderstood (AbstractException) >> _executeHandler: @4 line 8  [GsNMethod 4480513]
8 MessageNotUnderstood (AbstractException) >> _signalWith: @1 line 1  [GsNMethod 4473089]
9 MessageNotUnderstood (AbstractException) >> signal @2 line 47  [GsNMethod 4477953]
10 Set (Object) >> doesNotUnderstand: @10 line 10  [GsNMethod 4167937]
11 Set (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12  [GsNMethod 4170497]
12 [] in  ExecBlock1 (ExecBlock) >> on:do: @9 line 50  [GsNMethod 7171841]
13 MetacelloScriptGitBasedDownloadNotification (AbstractException) >> _executeHandler: @4 line 8  [GsNMethod 4480513]
14 MetacelloScriptGitBasedDownloadNotification (AbstractException) >> _signalWith: @1 line 1  [GsNMethod 4473089]
15 MetacelloScriptGitBasedDownloadNotification (AbstractException) >> signal @2 line 47  [GsNMethod 4477953]
16 MCGitHubRepository class (MCGitBasedNetworkRepository class) >> projectDirectoryFrom:version: @23 line 19  [GsNMethod 212939009]
17 MCGitHubRepository (MCGitBasedNetworkRepository) >> calculateRepositoryDirectory @6 line 5  [GsNMethod 212551425]
18 MCGitHubRepository (MCGitBasedNetworkRepository) >> validateLocalRepository @3 line 4  [GsNMethod 212543489]
19 MCGitHubRepository (MCGitBasedNetworkRepository) >> localRepository @4 line 3  [GsNMethod 212545025]
20 [] in  ExecBlock0 (MCGitBasedNetworkRepository) >> goferReferences @9 line 4  [GsNMethod 214699009]
21 ExecBlock0 (ExecBlock) >> onException:do: @2 line 66  [GsNMethod 4430593]
22 ExecBlock0 (ExecBlock) >> on:do: @5 line 49  [GsNMethod 4429825]
23 MCGitHubRepository (MCGitBasedNetworkRepository) >> goferReferences @3 line 5  [GsNMethod 212550657]
24 [] in  ExecBlock0 (Gofer) >> basicReferencesIn: @7 line 2  [GsNMethod 40642305]
25 ExecBlock0 (ExecBlock) >> on:do: @3 line 44  [GsNMethod 4429825]
26 MetacelloGofer (Gofer) >> basicReferencesIn: @3 line 3  [GsNMethod 35116289]
```

I get this in 5 tests (see https://travis-ci.org/jecisc/metacello/jobs/381182039)

Do you know what might be the problem? Because from the Pharo code I cannot find the problem.

**Comment by dalehenrich** [comment]
@jecisc in GemStone, the class **ExceptionSet** responds to `#handles:` ... an ExceptionSet is created when you use `#,` with an **Exception** ... so the **Set** must be used explicitly to create a collection of **Exceptions**?

**Comment by jecisc** [comment]
I have the impression esteban did not changed the code where the problem is raised, so it must be somewhere else... I'll try to see if I find the problem later.

**Comment by estebanlm** [comment]
yes, I didn’t touch that.

Esteban

**Comment by jecisc** [comment]
@dalehenrich `http://seaside.gemtalksystems.com/ss/metacello` seems down and so we cannot load Metacello.  

Do you know who manages it?

**Comment by jecisc** [comment]
@dalehenrich This is weird because I went over all the senders of #on:do: and all of them receive either an Exception or an ExceptionSet. 

I saw none providing a Set.

**Comment by jecisc** [comment]
Also here are all the try/catch I found in the stack:

```Smalltalk
goferReferences
	"delegate collection to local repository, but change them to be from *this* repository."
	| versionNames |
	versionNames := [ self localRepository allVersionNames ]
		on: MCRepositoryError
		do: [ :error | ^ GoferRepositoryError signal: error messageText repository: self ].
	^ versionNames collect: [ :each | GoferResolvedReference name: each repository: self ]
```

```Smalltalk
basicReferencesIn: aRepository
	^ [ aRepository goferReferences asSortedCollection asArray ] 
		on: GoferRepositoryError
		do: errorBlock
```

```Smalltalk
useStackCacheDuring: aBlock defaultDictionary: defaultDictionary
	| dict |
	dict := MetacelloStackCacheNotification signal.
	dict == nil
		ifTrue: [ 
			dict := defaultDictionary == nil
				ifTrue: [ Dictionary new ]
				ifFalse: [ defaultDictionary ] ].
	[ ^ aBlock value: dict ]
		on: MetacelloStackCacheNotification , MetacelloClearStackCacheNotification
		do: [ :ex | 
			(ex isKindOf: MetacelloStackCacheNotification)
				ifTrue: [ ex resume: dict ].
			(ex isKindOf: MetacelloClearStackCacheNotification)
				ifTrue: [ 
					| keys |
					keys := ex cacheNames.
					keys ifNil: [ keys := dict keys ].
					keys
						do: [ :k | 
							(dict includesKey: k)
								ifTrue: [ 
									| c |
									c := dict at: k.
									c keys do: [ :ck | c removeKey: ck ].
									dict removeKey: k ] ].
					ex resume ] ]
```

```Smalltalk
retryingResolvePackageSpecReferences: packageSpec gofer: gofer
    | retryCount references repositoryError |
    retryCount := 0.
    references := #().
    [ references isEmpty and: [ retryCount < 3 ] ]
        whileTrue: [ 
            retryCount > 0
                ifTrue: [ 
                    Transcript
                        cr;
                        show: '...RETRY->' , packageSpec file ].
            references := [ self resolvePackageSpecReferences: packageSpec gofer: gofer ]
                on: Error , GoferRepositoryError
                do: [ :ex | 
                    self class retryPackageResolution
                        ifFalse: [ ex pass ].
                    retryCount >= 2
                        ifTrue: [ 
                            (ex isKindOf: GoferRepositoryError)
                                ifTrue: [ 
                                    "ignore repository errors at this point, in case an alternate repository is in the list "
                                    Transcript
                                        cr;
                                        show: 'gofer repository error: ' , ex description printString , '...ignoring'.
                                    repositoryError := ex.
                                    ex resume: #() ]
                                ifFalse: [ ex pass ] ].
                    ex return: #() ].
            retryCount := retryCount + 1 ].
    references isEmpty
        ifTrue: [ 
            Transcript
                cr;
                show: '...FAILED->' , packageSpec file.
            (MetacelloPackageSpecResolutionError new
                packageSpec: packageSpec;
                repositories: gofer repositories;
                repositoryError: repositoryError;
                yourself) signal ].
    ^ references
```
As you can see, all of them have an Exception or an ExceptionSet and not a Set.

**Comment by estebanlm** [comment]
Ok, I finally got a green build.
Can this be merged, @dalehenrich ?

**Pull request merged**
