### PR TITLE
Silence deprecation warnings in tests.

### PR DESCRIPTION
**Pull request by krono**
SmalltalkImage>>#removeKey:ifAbsent: is Deprecated in Squeak (since
2010) and 'tobedeprecated' in Pharo for a very long time.

Uses `Smalltalk globals` now, which is preferred in the squeakish and
supported in GS.

### CODE REVIEW

**Comment by dalehenrich** [comment]
The GemStone2.4.8 error seems to be something new and is showing up in PR #455 and $456 ... Note that there are 30 some tests failing in Squeak builds and they seem to be the same tests that are failing in PR #455 ... I've put all of the Squeak builds into the expected failure section because I think these tests are failing consistently on travis-ci (headless) and I've been waiting for the headless issues to be cleaned up (or perhaps they never will?)

**Comment by krono** [comment]
Regarding the squeak tests: They do not fail for me locally, neither headful (see https://github.com/Metacello/metacello/pull/450#issuecomment-330685863 ) nor headless.
In this regard, they are not expected failures.

OTOH, the tests on travis 
 - use an old vm
 - are in THIS pr subject to rate limiting (see #458 ) (where also another tiny deprecation issue is fixed)

Lastly, I have just introduced a fix to WebClient with regards to bitbucket, related to some error.
 - These should now disappear 
 - At least, when #454 is merged, webclient won't be loaded or (unnecessarily) updated, which also circumvents the issue.

**Comment by dalehenrich** [comment]
Welll ... I was only guessing ... the [Squeak builds were moved to expected failures a year ago](https://github.com/Metacello/metacello/commit/8ea339bbd399aef7c78f49a881c3e0b27a94ba48) ... for "random failures" ... If you can get the headless vm tests to pass consistently then there should be no reason that the travis-ci builds should work identically and we can move the Squeak builds out of the expected failure zone!

**Comment by krono** [comment]
This depends on https://github.com/OpenSmalltalk/opensmalltalk-vm declaring a next stable version :(.
Whenever this is declared, we will update the vms and we can make this move…

**Comment by krono** [comment]
But I also thing this random failure stuff is not good.

This PR is but one step closer to make this better

**Comment by dalehenrich** [comment]
Agreed ... as I said in another thread I cleaned up the random failures (other than network-related errors) in the master branch a while ago... and that work very likely post-dated the configuration branch ... I would expect all tests to consistently pass on the master branch of Metacello ... IIRC (and I don't have a good track record for the Squeak failures:) one of the issue with random failure cleanup for GemStone/Pharo had to do with making sure that packages were properly deleted between tests ... lots of tests are checkin for the presence or absence of particular packages in the image and if a test does not properly delete a particular package, subsequent tests can be adversely affected --- if a test re-run passes, that is usually the root cause ... 

At this point we need to get to the point where only random test failures are remaining and I think at this point that is not the case ... once we're down to only random failures, we can instrument up the tests on travis to supply more detailed failure information (stacks, etc.) to attempt to isolate the random factors and eventually nail the tests down ..

**Comment by krono** [comment]
Merging for now, fixing those tests is important, but ultimately not related to this specific PR

**Pull request merged**
