### PR TITLE
- Introduce 1.0-beta.32.3 for bootstrap.

### LINKED ISSUE #438: Loading Metacello in Squeak loads an old version of WebClient
When loading Metacello into a fresh Squeak trunk image, a version of WebClient that is not up-to-date with the trunk is loaded. I assume this is because the Metacello baseline references another repository to fetch WebClient from. That repository does not contain the latest versions present in the Squeak trunk repository.

```
 "..."
 spec
    for: #'squeak'
    do: [ 
      "..."
      spec
        package: 'WebClient-Core'
        with: [ spec repository: 'http://ss3.gemstone.com/ss/WebClient' ].
      "..."
```

This may cause bugs in other, subsequently loaded software that depends on the newer WebClient versions. Workaround is to invoke the Squeak update again after installing Metacello.

### PR DESCRIPTION
**Pull request by krono**
(avoids loading WebClient/SqueakSSL in images where those are to be
  expected)
  -pick up private tfel.800 1.0-beta.32.2 which was patrly backported to
  1.0-beta.32.1.

Part I to fix #438

### CODE REVIEW

**Comment by krono** [comment]
Note: the MCZ for the bootstrap is ready to be put on ss3.

**Comment by krono** [comment]
@fniephaus @dalehenrich I don't understand this Travis Error, do you have a clue?

**Comment by fniephaus** [comment]
> User defined error, 'Cannot resolve symbolic version #''release1'''

See [here](https://travis-ci.org/Metacello/metacello/jobs/275456579#L757).

Does that help? Looks like your config/baseline is bogus...

**Comment by krono** [comment]
Ok, the configuration branch is still configured to use builderCI, so I have not clue at all what's going on here…

**Comment by dalehenrich** [comment]
Upon further review it looks it is probably an [issue with ConfigurationOfGrease](https://travis-ci.org/Metacello/metacello/jobs/275456579#L996)

**Comment by dalehenrich** [comment]
Okay I think I understand what is wrong with the ConfigurationOfGrease ...  from the transcript:

```
--transcript--'Fetched -> ConfigurationOfGrease-JohanBrichau.343 --- http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main --- http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main'
```

ConfigurationOfGrease-JohanBrichau.343 is loaded and a peak at the #release1: method (where the release1 symbolic version is being defined) in that version:

```Smalltalk
release1: aSpec
	<symbolicVersion:#'release1'>
	aSpec for: #(#'pharo3.x' #'pharo4.x' #'pharo5.x' #'pharo6.x' #'squeak5.x' #'gs3.x') version: #'release1.3'.
	aSpec for: #(#'pharo1.x' #'pharo2.x' #'squeak4.x' #'gs2.x') version: #'release1.2'
```

Shows that #for:version: is being used and it is very likely that the older version of Metacello being used at this point in the bootstrap does not support #for:version: ... 

So it might take some work from @jbrichau to address this particular problem ...

**Comment by jbrichau** [comment]
The reference repository for Grease is now https://github.com/SeasideSt/Grease (which does not have symbolic versions anymore) but I suppose that would not help advance the problem either?

Can you please tell me a bit more on what work is needed?

**Comment by dalehenrich** [comment]
We're getting a failure during the bootstrapping of Metacello into images that do not have a version of metacello/filetree installed that understands how to access github repos ... so the code is bootstrapping that particular capability via mcz packages ... `ConfigurationOfGrease-JohanBrichau.343` is begin picked up during the build and the #release1: method looks like the following:

```Smalltalk
release1: aSpec
	<symbolicVersion:#'release1'>
	aSpec for: #(#'pharo3.x' #'pharo4.x' #'pharo5.x' #'pharo6.x' #'squeak5.x' #'gs3.x') version: #'release1.3'.
	aSpec for: #(#'pharo1.x' #'pharo2.x' #'squeak4.x' #'gs2.x') version: #'release1.2'
```

and *I think* that `#for:version:` is not properly supported by the earlier versions of Metacello and this is the reason we are failing during the bootstrap ...

So I think that pushing a new version of ConfigurationOfGrease to 
`http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main` that explicitly maps the symbolic versions for each platform will allow us to get past this particular problem ... 

Thanks man! ... 

Missed you at ESUG this year ...

**Comment by jbrichau** [comment]
You mean that `#for:version:` is supported but not with the symbol **list** argument?

I can write full Smalltalk code in that method right? So doing an iteration should be easy to do. Or does it need to be a separate statement for each platform? (can do as well, but hey... you know :)

**Comment by dalehenrich** [comment]
On 09/18/2017 11:08 AM, Johan Brichau wrote:
>
> You mean that |#for:version:| is supported but not with the symbol 
> *list* argument?
>
Yes, I'm guessing that list argument is the problem ...  th

> I can write full Smalltalk code in that method right? So doing an 
> iteration should be easy to do. Or does it need to be a separate 
> statement for each platform? (can do as well, but hey... you know :)
>
I think that it's bes to do a single statement per platform and stay 
away from writing pure Smalltalk:) Hopefully this will be the last time 
you have to touch the ConfigurationOfGrease:)

**Comment by jbrichau** [comment]
If this is what is needed:
```
Name: ConfigurationOfGrease-JohanBrichau.344
Author: JohanBrichau
Time: 18 September 2017, 8:41:55.29852 pm
UUID: 99cf72d5-dc15-0d00-aa59-a363093fdeba
Ancestors: ConfigurationOfGrease-JohanBrichau.343

Change implementation of symbolic version methods to support loading with an older Metacello version (see discussion in https://github.com/Metacello/metacello/pull/450 )
```

**Comment by krono** [comment]
> On 18.09.2017, at 20:08, Johan Brichau <notifications@github.com> wrote:
> 
> You mean that #for:version: is supported but not with the symbol list argument?
> 
> I can write full Smalltalk code in that method right? So doing an iteration should be easy to do. Or does it need to be a separate statement for each platform? (can do as well, but hey... you know :)

Please let it not be that, because a list of platform symbols is actually what I introduced Into the bootstrap.

What is really strange is, that it worked for me.
I explicitely only changed squeak-specific stuff and there's no trace of Grease in there.

That's really strange…

Best regards
	-Tobias

**Comment by dalehenrich** [comment]
well this test was failing for all platforms, but I only looked in 
GemStone ... so what is more likely is that there are a number of 
failure mechanisms ... we haven't gone through this change of bootstrap 
for 2 years (right?) ... so there is a lot of dust to sift through ...

**Comment by krono** [comment]
Ok *grabs duster*

**Comment by dalehenrich** [comment]
Thanks Johan ... that looks good ...

**Comment by krono** [comment]
I restarted the build, let's see whether it helped…

**Comment by krono** [comment]
nope…

**Comment by krono** [comment]
One more thing: in the `travisCI.st` and the `travisPreviewCI.st`, it still refers to the old (?) repo name directly: https://github.com/Metacello/metacello/blob/configuration/tests/travisCI.st#L7 and https://github.com/Metacello/metacello/blob/configuration/tests/travisPreviewCI.st#L18
maybe that's putting things off?

**Comment by dalehenrich** [comment]
This is the part where we sift through the dust ... now we are past the ConfigurationOfGrease error (thanks @jbrichau) and into other issues ...

**Comment by krono** [comment]
Ok, this looks waay better

**Comment by dalehenrich** [comment]
Next step is to in-place edit the references to `http://seaside.gemstone.com/ss/metacello` and replace them with `http://seaside.gemtalksystems.com/ss/metacello` ... for all `gemstone.com` repos...

**Comment by StephanEggermont** [comment]
In Pharo 6.1, 343 works and 344 is broken

**Comment by StephanEggermont** [comment]
Name: ConfigurationOfGrease-StephanEggermont.345
Author: StephanEggermont
Time: 19 September 2017, 10:12:10.051757 am
UUID: b1131d27-e815-0d00-806a-08640829081c
Ancestors: ConfigurationOfGrease-JohanBrichau.344

Symbols instead of strings

**Comment by dalehenrich** [comment]
looks like the right fix, but re-running tests to be sure ...

**Comment by jbrichau** [comment]
Yes, these are Slime tests that started failing some weeks ago without changes in Grease itself. So, I propose to ignore them here.

**Comment by dalehenrich** [comment]
Sorry guys, I inadvertently merged this PR because [this comment](https://github.com/Metacello/metacello/pull/450#issuecomment-330600051) was in the wrong PR ... I thought I was in the Grease project...

Anyway, I reverted this PR so I think that @krono needs to submit a new PR ... to get us back on track

**Comment by jbrichau** [comment]
@dalehenrich sorry about that. I don't understand how my reply used that message. I replied on my phone and was pretty sure I replied to the right thread.... :(

**Comment by dalehenrich** [comment]
no problem, I should have looked a bit closer at the pr before pressing the merge button ... now I know that I have to be more careful ...

**Comment by dalehenrich** [comment]
@krono, it looks like you will have to re-merge the configuration branch into your config_dev branch before you can resubmit your pr ... in retrospect I should have undone the commit, since revert did not do what I expected it to do ... oh well ... live an learn ...

**Comment by dalehenrich** [comment]
@krono, it may be necessary to reapply your changes given the way that revert works ... if that is too difficult, perhaps we'll just nuke these last merge and revert commits on the configuration branch ... the configuration branch is pretty specialized so I don't think it will impact anyone else ...

**Comment by krono** [comment]
Ok, will do.

Just one more thing: Although we have a multitude of tests, quite some of them seem a bit wonky. 
For example, take the Squeak-4.5 results (30 failures), OTHO, locally, I get no failures and one error:
bildschirmfoto 2017-09-19 um 23 56 08

What do?

**Comment by krono** [comment]
(also, that error went away after re-running…)

**Comment by krono** [comment]
bildschirmfoto 2017-09-19 um 23 59 22

**Comment by dalehenrich** [comment]
I assume that you are talking about the tests for the configuration branch? This branch represents an intermediate step for the bootstrapping of the latest version of Metacello on github and the tests and implementation dates from several years ago ... all of the **wonky** tests should have been cleaned up in the latest version of Metacello. Eventually, the bootstrapping code will not be necessary (I hope).

**Pull request merged**
