### PR TITLE
Issue #367: Git Private Repository Authentication

### PR DESCRIPTION
**Pull request by seandenigris**
Respect `siteUsername:` and `sitePassword` when downloading Zips.
OT: Fix "Metacello-Platform" package pharo30 branch, which had incorrect meta-data incorrectly specifying the package name including the branch i.e. "Metacello-Platform.pharo30"

### CODE REVIEW

**Comment by seandenigris** [comment]
What needs to be done here?

**Comment by dalehenrich** [comment]
Given that there were a large number of test failures one step is to rerun the tests, but at the moment I am struggling with getting Squeak4.6 and Squeak5.0 added so I've prioritized doing that inform of this one ....

I haven't looked at all of the failing tests, so I don't know if there are additional issues or not ... the load failures are due to network failures and rerunning should show whether or there are actual code-based problems ...

**Comment by dalehenrich** [comment]
@seandenigris, when you get a chance can you make a minor change to a file (like add a line to the README.md)? I'm getting massive failures for tests and I'm not sure whether travis is just confused or something else is going on ... "pinging travis" will at least eliminate travis is confused ...

**Comment by davelab6** [comment]
I guess this should be closed

**Comment by dalehenrich** [comment]
Closing this PR - storing username/passwords in the image is not a good idea. the discussion in Issue #475 addresses the larger issue of enabling "first class access" to private repositories that require usernames and passwords ...

**Pull request closed without merging**
