### PR TITLE
fix tests for Pharo

### PR DESCRIPTION
**Pull request by estebanlm**
(it may need some iterations)

### CODE REVIEW

**Comment by estebanlm** [comment]
I have Pharo tests passing... but I don't know why Gemstone doesn't :(

**Comment by dalehenrich** [comment]
The error for GemStone 2.4.8 appears to be a recent issue ... it also shows up as an error in PR #455 tests as well ... I will have to look into this in more detail .. I should be able to reproduce this locally ..

**Comment by dalehenrich** [comment]
... the [recent updates to ConfigurationOfGrease](https://github.com/Metacello/metacello/pull/450#issuecomment-330464236) has introduced this problem for bootstrapping gs2.4 ....

**Comment by estebanlm** [comment]
can we merge this and fix the Gemstone problem later?

**Comment by dalehenrich** [comment]
Yeah ... the Grease problem affects GemStone 2.4.x with or without a new Metacello

**Comment by dalehenrich** [comment]
@estebanlm I see that this PR is just creating a pharo-6.1_dev branch in Metacello are you intending for this to be merged into the master branch or ???

**Comment by estebanlm** [comment]
I think we should do it... but again, I still don't know how metacello repo works, so you tell me ;)

**Comment by dalehenrich** [comment]
Okay ...for metacello I use a continuous integration model, where the master branch is the official release branch and all platforms should access the master branch to get the latest code... I am meticulous to avoid changing the API since I don't want to break anyone's scripts  ... so in the future doing development on a `pharo-6.1_dev` branch is a good idea, but when it comes time to open a PR, do the merge directly into the `master` branch ... and when all the tests pass, the merge to master is a new release of the project ... 

You should be able to open a PR from this branch to the master branch and I think you should have permissions to merge it when the tests are passing (I'll try to get the 2.4.8 problem cleaned up in the next day or two)... Let's give this a try to see that you do indeed have the permissions ... 

I may decide to set permissions up like the smalltalkCI project, but for now I'' trust you:)

**Pull request merged**
