### PR TITLE
Display the progress of zip downloads in Pharo

### PR DESCRIPTION
**Pull request by jecisc**

### CODE REVIEW

**Comment by jecisc** [comment]
Anyone to review/merge?

**Comment by dalehenrich** [comment]
if the fact that pharo-6.1 is failing is okay, I can press the button

**Comment by jecisc** [comment]
As I said in the other PR, I think that the fact that P6.1 is failing is not due to this PR. 

About this error on P6.1 job, it will probably be taken care with the PR from Esteban here: https://github.com/Metacello/metacello/pull/490

The Pharo 6.1 job is green and when gemstone and squeak will be too it will resolve the problem.

**Comment by jecisc** [comment]
@dalehenrich Thank you very much!

**Pull request merged**
