### PR TITLE
Add do:displaying: for the common Pharo

### PR DESCRIPTION
**Pull request by jecisc**
Wait the test of Travis before integration because I edited the files by hand.

### CODE REVIEW

**Comment by jecisc** [comment]
All green :)

**Comment by dalehenrich** [comment]
Okay I'll checkout out Pharo3.0 and Pharo4.0 with this change, can you do pharo5.0 and  pharo6.0?

**Comment by jecisc** [comment]
Yes. 

So I just execute this:

```Smalltalk
Metacello new
  baseline: 'Metacello';
  repository: 'github://jecisc/metacello:cf_add_do_displaying_to_pharo/repository';
  get.
Metacello new
  baseline: 'Metacello';
  repository: 'github://jecisc/metacello:cf_add_do_displaying_to_pharo/repository';
  onConflict: [:ex | ex allow];
  load
```

Then try to load another project through Metacello?

**Comment by dalehenrich** [comment]
I'm using:

``` smalltalk
Metacello image
baseline: 'Metacello';
load: 'Tests'
```

I run once without the change and then again to see if the progress bars appear to be consistent ... on Pharo3.0 it looks much better ...

**Comment by jecisc** [comment]
I updated and launched the loading of Seaside and it seems to works fine on Pharo 5.

Only problem is that sometimes I see two bar for the same info. 

See: https://puu.sh/ydkDM/99f9ec6fc3.png

**Comment by dalehenrich** [comment]
That would be a separate bug:) ... this might be showing the fetch and then load, although it implies nesting ... but a separate bug and something to be addressed later as I don't have that much time to track it down myself:)

**Comment by jecisc** [comment]
Pharo 5 seems to work fine. Trying Pharo 6.1 now.

**Comment by jecisc** [comment]
Pharo 6 seems fine too :)

**Comment by dalehenrich** [comment]
Pharo 4.0 loading seaside and saw doubling but the second line had a .mcz extensions so I think it was downloading the packageduring the fetch ... in 5.0 you might be loading from github, so there would be no .mcz extension ...

**Comment by dalehenrich** [comment]
okay lets ship it ... I'll update the tags for 6.1 and 7.0

**Pull request merged**
